### ISSUE TITLE
Enable using easy-imgui-window without giving it ownership of the window

### ISSUE THREAD

**Issue by rodrigorc** [rodrigorc/easy-imgui-rs#3]
In #2  @Latias94 suggests making `easy-imgui-window` usable without giving it the ownership of the main window.

**Comment by rodrigorc** [comment]
Hey @Latias94, I've pushed a new commit to the `WindowRef` branch. This has a free function `do_event` that takes the pieces of the main window separately.

You'll probably need to implement the `MainWindowRef` for whatever type you have holding the main window, or for a new-type.

What do you think? Will that work for you? If not, maybe you could try sharing a branch of your repository with some attempt?

**Comment by Latias94** [comment]
I'm truly grateful for your prompt response. Perhaps my earlier communication wasn't as clear as it could have been. For my purposes, I prefer having the autonomy to decide when to invoke methods like initialization, prepare_frame, and prepare_render, akin to the flexibility seen in the example at [https://github.com/imgui-rs/imgui-rs/blob/main/imgui-glow-renderer/examples/glow_01_basic.rs](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-glow-renderer/examples/glow_01_basic.rs). Here, I have the freedom to determine the timing of a few crucial method calls needed for the renderer and event_handler (from the imgui-winit-support crate).

Thus, I believe a more suitable approach would be to externalize event handling, similar to what is done here: https://github.com/imgui-rs/imgui-rs/blob/main/imgui-winit-support/src/lib.rs. This way, I wouldn't need to implement additional traits. Instead, I could simply incorporate one or two imgui structures within my App structure and call their methods at the appropriate times, facilitating seamless integration.

Here's how I integrated egui into my code: https://github.com/Latias94/learn_opengl_rs/blob/main/src/window.rs#L307-L394. Although my renderer implementation may not be optimal, it works!

**Comment by Latias94** [comment]
To put it simply, if one is developing an Imgui App, using the MainWindow structure is a good choice. However, for integrating Imgui, I would appreciate having a crate that could help reduce the tediousness of handling Imgui events. If the event handling code were to be abstracted away, then for users to employ this code to write their own MainWindow wouldn't be a cumbersome task.

**Comment by rodrigorc** [comment]
> Perhaps my earlier communication wasn't as clear as it could have been. 
I think you explained the situation well enough. But for me, having the code is always easier to understand.

I've looked at your repo, and did some work... pushed another commit to my MainWindowRef branch, to implement the trait directly for a `winit::Window`.

I had to change your `Arc<GlContext>` for a `Rc<GlContext>` that is required by `easy-imgui-renderer`. But `GlContext` is not `Sync`, so `Arc` here makes little sense (there is a clippy lint for that).

Also, it looks like the `game_loop` crate separates render events from other events, so I have to call to the render manually. 

Then, I took the liberty to created a [PR][1] to your repo with the change. I think it is not ideal: there are some issues pending, I think resizing the window does not work properly, closing requests are sometimes ignored, hidpi isn't even considered, but it works!! What do you think?

[1]: https://github.com/Latias94/learn_opengl_rs/pull/1

**Comment by Latias94** [comment]
Thanks for your work and the PR! I used Arc because egui_glow::new needs it (https://docs.rs/egui_glow/latest/egui_glow/winit/struct.EguiGlow.html#method.new), but I'm not sure why it's different. FYI, imgui_glow use Rc<GlContext> as well.

Glad it's running! I'll look into modifying easy_imgui_window to better align with my vision when I have time. About the DPI issue, I didn't have this problem with egui, so it's strange. Do you know how to fix it?

**Comment by rodrigorc** [comment]
Hey @Latias94!

I have just pushed a commit to the `MainWindowRef` branch with a very basic `game_loop` example and a few other improvements. I think the hidpi issue is fixed now (the default ImGui font doesn't seem to scale, though).

I'm using my `MainWindow` type for initialization only, any `winit` window should work just the same. Also the game itself, that shown behind the ImGui UI is quite lame (patches welcome  :smile:).

The new public API is just a proposal, but if you find the time, can you test it and tell me what you think? Does it fit with your code?

**Comment by Latias94** [comment]
I'd like to apologize for my delayed response; I've been incredibly busy lately。

I've submitted a merge request https://github.com/rodrigorc/easy-imgui-rs/pull/4 to share my approach towards achieving the functionality of your `MainWindow` with minimal code and without implementing traits. The reason I'm avoiding traits is due to my project `learn_opengl_rs`, where I prefer not to require each example to re-implement traits just to handle UI rendering.

Additionally, I must admit that I'm not very familiar with ImGui itself, so my handling of scale factors and cursor positioning in the MR might not be entirely accurate.

**Comment by rodrigorc** [comment]
Hello!

I have just pushed a few commits to the `WindowRef` branch, polishing the public API, I think it looks quite nice now. Also I have force-pushed that PR https://github.com/Latias94/learn_opengl_rs/pull/1 for illustration purposes.

And now you can even call `easy_imgui_window::do_event()` by just having a `winit::Window`, if the pre/post render and the resizing are handled elsewhere.

About that problem you commented of not being able to build the UI without implemented a the trait `UiBuilder` I tried doing something but it is not so easy, because my `Ui<T>` that wraps an ImGui frame is generic, being the `T` the type that implements `UiBuilder`... changing that would require a lot of refactoring.

That generic `Ui<T>` is required to properly implement ImGui callbacks. I admit that it isn't ideal, but at least it is _easy_ to use.

**Comment by rodrigorc** [comment]
Hello again, @Latias94.

I've merged the `WindowRef` branch to master, polished it a bit and added documentation. Consider it a `0.3.0` release candidate. I think that it mostly does what you need, even if not exactly with the desired syntax.

I've also force-pushed my PR to your example code, to illustrate how it could work, this time with an optional feature, just like you do with `egui`. It is not as straight-forward, because of that `UiBuilder` trait, but I think it is not so bad.

**Comment by Latias94** [comment]
> Hello again, @Latias94.
> 
> I've merged the `WindowRef` branch to master, polished it a bit and added documentation. Consider it a `0.3.0` release candidate. I think that it mostly does what you need, even if not exactly with the desired syntax.
> 
> I've also force-pushed my PR to your example code, to illustrate how it could work, this time with an optional feature, just like you do with `egui`. It is not as straight-forward, because of that `UiBuilder` trait, but I think it is not so bad.

Thank you! I've merged the MR. Although there are some high DPI issues, I think it's already pretty good.
![image](https://github.com/rodrigorc/easy-imgui-rs/assets/13315417/ca7e146d-961a-45eb-ab81-722b2fc47d55)

**Comment by rodrigorc** [comment]
I have just published version 0.3.0 of `easy-imgui`. I think this mostly fixes what you need, @Latias94. So I think this issue can be closed.

Your issues with HiDPI may happen because you are not resizing the surface on "size" events. That is because you are using the `MainWindowRef` that doesn't know about the surface, so you are opting out of that behaviour. Also I think you are not recomputing the GL matrix or the viewport or something...

**Comment by Latias94** [comment]
fixed with https://github.com/Latias94/learn_opengl_rs/commit/36f87dc202e9639d0dc85f9afac17245a54466aa
